apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  domain: "localhost"
  aws-default-region: "us-east-1"
  aws-account-id: "000000000000"
  aws-service-url: "http://ittrap-localstack-service:4566"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  outbound-sns-topic-arn: "arn:aws:sns:us-east-1:000000000000:user-events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
data:
  sqs-url: "http://ittrap-localstack-service:4566/000000000000/auth-queue"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
data:
  default-region: "us-east-1"
  management-queue: "management-queue"
  auth-queue: "auth-queue"
  user-topic: "user-events"
  item-topic: "item-events"
  auth-topic: "auth-events"
  location-topic: "location-events"
  localstack-host: "ittrap-localstack-service:4566"