apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  domain: "localhost"
  aws-default-region: "eu-central-1"
  aws-account-id: "000000000000"
  aws-service-url: "http://ittrap-localstack-service:4566"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  outbound-sns-topic-arn: "arn:aws:sns:eu-central-1:000000000000:user-events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
data:
  sqs-url: "http://ittrap-localstack-service:4566/000000000000/auth-queue"
  outbound-sns-topic-arn: "arn:aws:sns:eu-central-1:000000000000:auth-events"
  email-server-address: "http://ittrap-email-service:80"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
data:
  sqs-url: "http://ittrap-localstack-service:4566/000000000000/query-queue"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
data:
  outbound-sns-topic-arn: "arn:aws:sns:eu-central-1:000000000000:item-events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-service-config
data:
  outbound-sns-topic-arn: "arn:aws:sns:eu-central-1:000000000000:location-events"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: management-service-config
data:
  outbound-sns-topic-arn: "arn:aws:sns:eu-central-1:000000000000:management-events"
  sqs-url: "http://ittrap-localstack-service:4566/000000000000/management-queue"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-config
data:
  default-region: "eu-central-1"
  management-queue: "management-queue"
  auth-queue: "auth-queue"
  query-queue: "query-queue"
  user-topic: "user-events"
  item-topic: "item-events"
  auth-topic: "auth-events"
  location-topic: "location-events"
  management-topic: "management-events"
  localstack-host: "ittrap-localstack-service:4566"
