{{- if .Values.services.apiGateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ittrap-api-gateway
  namespace: {{ include "ittrap.namespace" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittrap-api-gateway
  namespace: {{ include "ittrap.namespace" . }}
  labels:
    app.kubernetes.io/name: ittrap
    app.kubernetes.io/component: api-gateway
spec:
  replicas: {{ .Values.services.apiGateway.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ittrap
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ittrap
        app.kubernetes.io/component: api-gateway
    spec:
      serviceAccountName: ittrap-api-gateway
      containers:
        - name: ittrap-api-gateway
          image: "{{ .Values.services.apiGateway.image.repository }}:{{ .Values.services.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.services.apiGateway.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: GlobalConfig__Domain
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: domain
            - name: GlobalConfig__JwtPrivateKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.globalConfigSecretName }}
                  key: jwt-private-key
          resources:
{{ toYaml .Values.services.apiGateway.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-api-gateway
  namespace: {{ include "ittrap.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ittrap
    app.kubernetes.io/component: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}

