{{- if .Values.services.emailService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ittrap-email-service
  namespace: {{ include "ittrap.namespace" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittrap-email-service
  namespace: {{ include "ittrap.namespace" . }}
  labels:
    app.kubernetes.io/name: ittrap
    app.kubernetes.io/component: email-service
spec:
  replicas: {{ .Values.services.emailService.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ittrap
      app.kubernetes.io/component: email-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ittrap
        app.kubernetes.io/component: email-service
    spec:
      serviceAccountName: ittrap-email-service
      containers:
        - name: ittrap-email-service
          image: "{{ .Values.services.emailService.image.repository }}:{{ .Values.services.emailService.image.tag }}"
          imagePullPolicy: {{ .Values.services.emailService.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "80"
            - name: GlobalConfig__Smtp__Host
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: host
            - name: GlobalConfig__Smtp__Port
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: port
            - name: GlobalConfig__Smtp__Username
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: username
            - name: GlobalConfig__Smtp__Password
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: password
            - name: GlobalConfig__Smtp__FromEmail
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: fromEmail
            - name: GlobalConfig__Smtp__FromName
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: fromName
            - name: GlobalConfig__Smtp__UseSsl
              valueFrom:
                secretKeyRef:
                  name: email-service-config
                  key: useSsl
          resources:
{{ toYaml .Values.services.emailService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-email-service
  namespace: {{ include "ittrap.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ittrap
    app.kubernetes.io/component: email-service
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}

