apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: postgres-config
    creationPolicy: Owner
  data:
    - secretKey: postgres-user
      remoteRef:
        key: ittrap/postgres
        property: postgres-user
    - secretKey: postgres-password
      remoteRef:
        key: ittrap/postgres
        property: postgres-password
    - secretKey: postgres-database
      remoteRef:
        key: ittrap/postgres
        property: postgres-database
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: global-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: global-config
    creationPolicy: Owner
  data:
    - secretKey: jwt-private-key
      remoteRef:
        key: ittrap/global
        property: jwt-private-key
    - secretKey: mediatr-license-key
      remoteRef:
        key: ittrap/global
        property: mediatr-license-key
    - secretKey: admin-email
      remoteRef:
        key: ittrap/global
        property: admin-email
    - secretKey: admin-phone
      remoteRef:
        key: ittrap/global
        property: admin-phone
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: aws-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: ittrap/aws
        property: access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: ittrap/aws
        property: secret-access-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: user-service-config
    creationPolicy: Owner
  data:
    - secretKey: postgreSqlConnectionString
      remoteRef:
        key: ittrap/user-service-config
        property: postgreSqlConnectionString
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-service-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: identity-service-config
    creationPolicy: Owner
  data:
    - secretKey: postgreSqlConnectionString
      remoteRef:
        key: ittrap/identity-service-config
        property: postgreSqlConnectionString
    - secretKey: passwordPepper
      remoteRef:
        key: ittrap/identity-service-config
        property: passwordPepper
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventory-service-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: inventory-service-config
    creationPolicy: Owner
  data:
    - secretKey: postgreSqlConnectionString
      remoteRef:
        key: ittrap/inventory-service-config
        property: postgreSqlConnectionString
    - secretKey: mongoDbConnectionString
      remoteRef:
        key: ittrap/inventory-service-config
        property: mongoDbConnectionString
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inventory-mongo-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: inventory-mongo-config
    creationPolicy: Owner
  data:
    - secretKey: mongo-initdb-root-username
      remoteRef:
        key: ittrap/mongo
        property: mongo-initdb-root-username
    - secretKey: mongo-initdb-root-password
      remoteRef:
        key: ittrap/mongo
        property: mongo-initdb-root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: location-service-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: location-service-config
    creationPolicy: Owner
  data:
    - secretKey: postgreSqlConnectionString
      remoteRef:
        key: ittrap/location-service-config
        property: postgreSqlConnectionString
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: management-service-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: management-service-config
    creationPolicy: Owner
  data:
    - secretKey: postgreSqlConnectionString
      remoteRef:
        key: ittrap/management-service-config
        property: postgreSqlConnectionString
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email-service-config
  namespace: {{ include "ittrap.namespace" . }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: email-service-config
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: ittrap/smtp
        property: host
    - secretKey: port
      remoteRef:
        key: ittrap/smtp
        property: port
    - secretKey: username
      remoteRef:
        key: ittrap/smtp
        property: username
    - secretKey: password
      remoteRef:
        key: ittrap/smtp
        property: password
    - secretKey: fromEmail
      remoteRef:
        key: ittrap/smtp
        property: fromEmail
    - secretKey: fromName
      remoteRef:
        key: ittrap/smtp
        property: fromName
    - secretKey: useSsl
      remoteRef:
        key: ittrap/smtp
        property: useSsl