{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ittrap-api-gateway
  namespace: {{ include "ittrap.namespace" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.host }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: ittrap-api-gateway
                port:
                  number: 80
          {{- end }}
  {{- else }}
  defaultBackend:
    service:
      name: ittrap-api-gateway
      port:
        number: 80
  {{- end }}
{{- end }}

