{{- if .Values.mailhog.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ittrap-mailhog
  namespace: {{ include "ittrap.namespace" . }}
  labels:
    app.kubernetes.io/name: ittrap
    app.kubernetes.io/component: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ittrap
      app.kubernetes.io/component: mailhog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ittrap
        app.kubernetes.io/component: mailhog
    spec:
      containers:
        - name: mailhog
          image: "{{ .Values.mailhog.image.repository }}:{{ .Values.mailhog.image.tag }}"
          imagePullPolicy: {{ .Values.mailhog.image.pullPolicy }}
          ports:
            - containerPort: 1025
            - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: ittrap-mailhog-service
  namespace: {{ include "ittrap.namespace" . }}
spec:
  type: {{ .Values.mailhog.service.type }}
  selector:
    app.kubernetes.io/name: ittrap
    app.kubernetes.io/component: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: http
      port: 8025
      targetPort: 8025
{{- end }}

