apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-vault-auth
  namespace: {{ include "ittrap.namespace" . }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
  namespace: {{ include "ittrap.namespace" . }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "ittrap-eso"
          serviceAccountRef:
            name: eso-vault-auth
